name: mapolato
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.9.0
  phone_input: ^1.0.0
  intl: ^0.20.2
  fl_chart: ^1.0.0
  auto_size_text: ^3.0.0
  rive: ^0.13.20
  table_calendar: ^3.2.0
  logger: ^2.6.1
  workmanager: ^0.9.0+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  dcm: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/rive/