// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHekm0zWiZ7gBoq-3TX1yGw3tbOeUFGsU',
    appId: '1:472013534602:web:97f81f32ebd5968fc84473',
    messagingSenderId: '472013534602',
    projectId: 'mapolato-27709',
    authDomain: 'mapolato-27709.firebaseapp.com',
    storageBucket: 'mapolato-27709.firebasestorage.app',
    measurementId: 'G-J7FZNELB3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZLxLUypOHoV2bY9GmJzqemPiVk5PfbLs',
    appId: '1:472013534602:android:5c63f93197441be6c84473',
    messagingSenderId: '472013534602',
    projectId: 'mapolato-27709',
    storageBucket: 'mapolato-27709.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHekm0zWiZ7gBoq-3TX1yGw3tbOeUFGsU',
    appId: '1:472013534602:web:ba2a464d3235f7fdc84473',
    messagingSenderId: '472013534602',
    projectId: 'mapolato-27709',
    authDomain: 'mapolato-27709.firebaseapp.com',
    storageBucket: 'mapolato-27709.firebasestorage.app',
    measurementId: 'G-HNV8P53G8G',
  );
}
